name: Deploy site on DigitalOcean App Platform

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  create-envfile:
    runs-on: ubuntu-latest

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          CI_ENVIRONMENT: production
          app.baseURL: "https://example.ondigitalocean.app/"
          app_baseURL: "https://example.ondigitalocean.app/"

          database.default.hostname: 24.199.106.12
          database.default.database: efpem_lms
          database.default.username: admin

          ENCRYPTION_SALT: 37f92da155a27424f3ad

      - uses: 1arp/create-a-file-action@0.3
        with:
          path: "./"
          file: "foo.bar"
          content: |
            Hello
            World

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jjst/action-digitalocean-deploy-app@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          app-id: ${{ secrets.DIGITALOCEAN_APP_ID }}
          app_name: sea-turtle-app

      - uses: actions/checkout@v2
